# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1URRZjxyOXRqTwp_9bAr3UO_p4U53hoHS
"""

import streamlit as st
import pandas as pd
import joblib

# Cargar modelo
modelo = joblib.load('modelo_telco_churn.pkl')

st.title("Predicción de Abandono de Clientes - Telco")

st.write("Ingrese los datos del cliente:")

# Entradas del usuario
Contrato = st.selectbox("Tipo de contrato", ["Month-to-month", "One year", "Two year"])
ServicioInternet = st.selectbox("Servicio de Internet", ["DSL", "Fiber optic", "No"])
MetodoPago = st.selectbox("Método de pago", [
    "Electronic check",
    "Mailed check",
    "Bank transfer (automatic)",
    "Credit card (automatic)"
])
Permanencia = st.slider("Permanencia (meses)", 0, 72, 12)
CargosMensuales = st.number_input("Cargos mensuales", min_value=0.0, value=70.0)
CargosTotales = st.number_input("Cargos totales", min_value=0.0, value=1000.0)

# Crear DataFrame
datos_cliente = pd.DataFrame([{
    "Contrato": Contrato,
    "ServicioInternet": ServicioInternet,
    "MetodoPago": MetodoPago,
    "Permanencia": Permanencia,
    "CargosMensuales": CargosMensuales,
    "CargosTotales": CargosTotales
}])

if st.button("Predecir abandono"):
    prob = modelo.predict_proba(datos_cliente)[0][1]

    st.subheader(f"Probabilidad de abandono: {prob:.2%}")

    if prob >= 0.70:
        st.error("🔴 Riesgo ALTO de abandono")
        st.write("👉 Recomendación: ofrecer descuento o migrar a contrato anual.")
    elif prob >= 0.40:
        st.warning("🟠 Riesgo MEDIO de abandono")
        st.write("👉 Recomendación: enviar promociones personalizadas.")
    else:
        st.success("🟢 Riesgo BAJO de abandono")
        st.write("👉 Recomendación: mantener estrategia actual.")